# A style to ID encoding
encode_style = {'Altbier': 74,
 'American Adjunct Lager': 1,
 'American Amber / Red Ale': 68,
 'American Amber / Red Lager': 12,
 'American Barleywine': 78,
 'American Black Ale': 48,
 'American Blonde Ale': 14,
 'American Brown Ale': 38,
 'American Dark Wheat Ale': 44,
 'American Double / Imperial IPA': 63,
 'American Double / Imperial Pilsner': 65,
 'American Double / Imperial Stout': 61,
 'American IPA': 88,
 'American Malt Liquor': 28,
 'American Pale Ale (APA)': 37,
 'American Pale Lager': 76,
 'American Pale Wheat Ale': 69,
 'American Porter': 24,
 'American Stout': 26,
 'American Strong Ale': 92,
 'American Wild Ale': 17,
 'Baltic Porter': 58,
 'Belgian Dark Ale': 18,
 'Belgian IPA': 90,
 'Belgian Pale Ale': 15,
 'Belgian Strong Dark Ale': 55,
 'Belgian Strong Pale Ale': 77,
 'Berliner Weissbier': 59,
 'Bière de Champagne / Bière Brut': 31,
 'Bière de Garde': 4,
 'Black & Tan': 23,
 'Bock': 102,
 'Braggot': 66,
 'California Common / Steam Beer': 95,
 'Chile Beer': 57,
 'Cream Ale': 70,
 'Czech Pilsener': 64,
 'Doppelbock': 52,
 'Dortmunder / Export Lager': 32,
 'Dubbel': 43,
 'Dunkelweizen': 62,
 'Eisbock': 46,
 'English Barleywine': 10,
 'English Bitter': 9,
 'English Brown Ale': 7,
 'English Dark Mild Ale': 42,
 'English India Pale Ale (IPA)': 47,
 'English Pale Ale': 98,
 'English Pale Mild Ale': 45,
 'English Porter': 49,
 'English Stout': 72,
 'English Strong Ale': 41,
 'Euro Dark Lager': 25,
 'Euro Pale Lager': 97,
 'Euro Strong Lager': 84,
 'Extra Special / Strong Bitter (ESB)': 21,
 'Faro': 51,
 'Flanders Oud Bruin': 96,
 'Flanders Red Ale': 33,
 'Foreign / Export Stout': 83,
 'Fruit / Vegetable Beer': 87,
 'German Pilsener': 2,
 'Gose': 103,
 'Gueuze': 39,
 'Happoshu': 6,
 'Hefeweizen': 99,
 'Herbed / Spiced Beer': 79,
 'Irish Dry Stout': 19,
 'Irish Red Ale': 8,
 'Japanese Rice Lager': 30,
 'Keller Bier / Zwickel Bier': 20,
 'Kristalweizen': 82,
 'Kvass': 11,
 'Kölsch': 29,
 'Lambic - Fruit': 80,
 'Lambic - Unblended': 53,
 'Light Lager': 91,
 'Low Alcohol Beer': 93,
 'Maibock / Helles Bock': 81,
 'Milk / Sweet Stout': 75,
 'Munich Dunkel Lager': 22,
 'Munich Helles Lager': 34,
 'Märzen / Oktoberfest': 0,
 'Oatmeal Stout': 86,
 'Old Ale': 89,
 'Pumpkin Ale': 50,
 'Quadrupel (Quad)': 40,
 'Rauchbier': 101,
 'Roggenbier': 16,
 'Russian Imperial Stout': 13,
 'Rye Beer': 35,
 'Sahti': 54,
 'Saison / Farmhouse Ale': 3,
 'Schwarzbier': 36,
 'Scotch Ale / Wee Heavy': 85,
 'Scottish Ale': 67,
 'Scottish Gruit / Ancient Herbed Ale': 60,
 'Smoked Beer': 100,
 'Tripel': 73,
 'Vienna Lager': 71,
 'Weizenbock': 27,
 'Wheatwine': 5,
 'Winter Warmer': 56,
 'Witbier': 94}
